version: '2'

services:
  preferencecreate:
    image: 'user-preference-create-update:userPreference1.0'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: preferencecreate
    depends_on:
      - postgres
    links:
      - postgres

  preferencefetch:
    image: 'user-preference-fetch:userPreference1.0'
    ports:
      - "8081:8081"
    build:
      context: .
    container_name: preferencefetch
    networks:
      - preference-network
    depends_on:
      - preferencecreate
      - postgres
    links:
      - postgres

  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    container_name: postgres
    volumes:
        - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    network_mode: bridge

networks:
  preference-network:

volumes:
  postgres-data: